"""Add car image and pricing

Revision ID: 68034215a188
Revises: 3ede5da64c72
Create Date: 2025-04-24 13:45:24.395221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68034215a188'
down_revision = '3ede5da64c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
