"""cars table

Revision ID: 7d2f595e02a6
Revises: 0fe38ef10866
Create Date: 2024-05-20 13:09:55.887904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2f595e02a6'
down_revision = '0fe38ef10866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('mileage',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=140),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_car_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('seats')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seats', sa.INTEGER(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_car_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('mileage',
               existing_type=sa.String(length=140),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
