"""add column to car table

Revision ID: d6dd9f51b7a2
Revises: a8b416b8dd13
Create Date: 2023-12-17 14:57:14.062411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6dd9f51b7a2'
down_revision = 'a8b416b8dd13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_type', sa.String(length=140), nullable=False))
        batch_op.add_column(sa.Column('mileage', sa.String(length=140), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('mileage')
        batch_op.drop_column('fuel_type')

    # ### end Alembic commands ###
