"""add column changes to car table

Revision ID: e83fff95edba
Revises: d6dd9f51b7a2
Create Date: 2023-12-17 15:02:20.157362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83fff95edba'
down_revision = 'd6dd9f51b7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seats', sa.Integer(), nullable=False))
        batch_op.alter_column('mileage',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('mileage',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)
        batch_op.drop_column('seats')

    # ### end Alembic commands ###
