"""Add Booking table

Revision ID: eb039c5b9e3b
Revises: 6c2d111862fb
Create Date: 2025-02-22 19:11:25.063810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb039c5b9e3b'
down_revision = '6c2d111862fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('renter_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.ForeignKeyConstraint(['renter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_car_id'), ['car_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_renter_id'), ['renter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_start_date'), ['start_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_start_date'))
        batch_op.drop_index(batch_op.f('ix_booking_renter_id'))
        batch_op.drop_index(batch_op.f('ix_booking_end_date'))
        batch_op.drop_index(batch_op.f('ix_booking_car_id'))

    op.drop_table('booking')
    # ### end Alembic commands ###
